
// This file has been generated by the GUI designer. Do not modify.
namespace MagnumHouse
{
	public partial class PhysicsAdjuster
	{
		private global::Gtk.Notebook notebook;

		private global::Gtk.VBox vbox1;

		private global::Gtk.DrawingArea statsArea;

		private global::Gtk.Expander expander1;

		private global::Gtk.Label label16;

		private global::Gtk.Label GtkLabel1;

		private global::Gtk.Label label5;

		private global::Gtk.Table table1;

		private global::Gtk.ToggleButton drawBBsToggleButton;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button plusSizeButton;

		private global::Gtk.Button minusSizeButton;

		private global::Gtk.Label label1;

		private global::Gtk.Label label15;

		private global::Gtk.Label label2;

		private global::Gtk.Button restartLevelButton;

		private global::Gtk.Label sizeLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MagnumHouse.PhysicsAdjuster
			this.Name = "MagnumHouse.PhysicsAdjuster";
			this.Title = global::Mono.Unix.Catalog.GetString ("PhysicsAdjuster");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MagnumHouse.PhysicsAdjuster.Gtk.Container+ContainerChild
			this.notebook = new global::Gtk.Notebook ();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 1;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statsArea = new global::Gtk.DrawingArea ();
			this.statsArea.Name = "statsArea";
			this.vbox1.Add (this.statsArea);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statsArea]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander (null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("red = speed, blue = acceleration");
			this.label16.Wrap = true;
			this.expander1.Add (this.label16);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("key");
			this.GtkLabel1.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel1;
			this.vbox1.Add (this.expander1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.expander1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.notebook.Add (this.vbox1);
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("stats");
			this.notebook.SetTabLabel (this.vbox1, this.label5);
			this.label5.ShowAll ();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.drawBBsToggleButton = new global::Gtk.ToggleButton ();
			this.drawBBsToggleButton.CanFocus = true;
			this.drawBBsToggleButton.Name = "drawBBsToggleButton";
			this.drawBBsToggleButton.UseUnderline = true;
			this.drawBBsToggleButton.Label = global::Mono.Unix.Catalog.GetString ("draw bbs");
			this.table1.Add (this.drawBBsToggleButton);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.drawBBsToggleButton]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.plusSizeButton = new global::Gtk.Button ();
			this.plusSizeButton.CanFocus = true;
			this.plusSizeButton.Name = "plusSizeButton";
			this.plusSizeButton.UseUnderline = true;
			this.plusSizeButton.Label = global::Mono.Unix.Catalog.GetString ("+");
			this.hbox1.Add (this.plusSizeButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.plusSizeButton]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.minusSizeButton = new global::Gtk.Button ();
			this.minusSizeButton.CanFocus = true;
			this.minusSizeButton.Name = "minusSizeButton";
			this.minusSizeButton.UseUnderline = true;
			this.minusSizeButton.Label = global::Mono.Unix.Catalog.GetString ("-");
			this.hbox1.Add (this.minusSizeButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.minusSizeButton]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.table1.Add (this.hbox1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox1]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("draw bbs");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Size");
			this.table1.Add (this.label15);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label15]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("restart");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.restartLevelButton = new global::Gtk.Button ();
			this.restartLevelButton.CanFocus = true;
			this.restartLevelButton.Name = "restartLevelButton";
			this.restartLevelButton.UseUnderline = true;
			this.restartLevelButton.Label = global::Mono.Unix.Catalog.GetString ("restart");
			this.table1.Add (this.restartLevelButton);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.restartLevelButton]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook.Add (this.table1);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.table1]));
			w13.Position = 1;
			// Notebook tab
			this.sizeLabel = new global::Gtk.Label ();
			this.sizeLabel.Name = "sizeLabel";
			this.sizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("me gangster");
			this.notebook.SetTabLabel (this.table1, this.sizeLabel);
			this.sizeLabel.ShowAll ();
			this.Add (this.notebook);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 467;
			this.DefaultHeight = 473;
			this.Show ();
			this.statsArea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.drawStatsArea);
			this.restartLevelButton.Activated += new global::System.EventHandler (this.restartButtonClicked);
			this.plusSizeButton.Clicked += new global::System.EventHandler (this.plusSizeButtonClicked);
			this.minusSizeButton.Clicked += new global::System.EventHandler (this.minusSizeButtonClicked);
			this.drawBBsToggleButton.Toggled += new global::System.EventHandler (this.drawBoundingBoxesToggled);
		}
	}
}
