// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagnumHouse {
    
    
    public partial class PhysicsAdjuster {
        
        private Gtk.Notebook notebook;
        
        private Gtk.VBox vbox1;
        
        private Gtk.DrawingArea statsArea;
        
        private Gtk.Expander expander1;
        
        private Gtk.Label label16;
        
        private Gtk.Label GtkLabel1;
        
        private Gtk.Label label5;
        
        private Gtk.Table table1;
        
        private Gtk.ToggleButton drawBBsToggleButton;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button plusSizeButton;
        
        private Gtk.Button minusSizeButton;
        
        private Gtk.Label label1;
        
        private Gtk.Label label15;
        
        private Gtk.Label label2;
        
        private Gtk.Button restartLevelButton;
        
        private Gtk.Label sizeLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MagnumHouse.PhysicsAdjuster
            this.Name = "MagnumHouse.PhysicsAdjuster";
            this.Title = Mono.Unix.Catalog.GetString("PhysicsAdjuster");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child MagnumHouse.PhysicsAdjuster.Gtk.Container+ContainerChild
            this.notebook = new Gtk.Notebook();
            this.notebook.CanFocus = true;
            this.notebook.Name = "notebook";
            this.notebook.CurrentPage = 1;
            // Container child notebook.Gtk.Notebook+NotebookChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.statsArea = new Gtk.DrawingArea();
            this.statsArea.Name = "statsArea";
            this.vbox1.Add(this.statsArea);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.statsArea]));
            w1.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.expander1 = new Gtk.Expander(null);
            this.expander1.CanFocus = true;
            this.expander1.Name = "expander1";
            this.expander1.Expanded = true;
            // Container child expander1.Gtk.Container+ContainerChild
            this.label16 = new Gtk.Label();
            this.label16.Name = "label16";
            this.label16.LabelProp = Mono.Unix.Catalog.GetString("red = speed, blue = acceleration");
            this.label16.Wrap = true;
            this.expander1.Add(this.label16);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("key");
            this.GtkLabel1.UseUnderline = true;
            this.expander1.LabelWidget = this.GtkLabel1;
            this.vbox1.Add(this.expander1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.expander1]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.notebook.Add(this.vbox1);
            // Notebook tab
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("stats");
            this.notebook.SetTabLabel(this.vbox1, this.label5);
            this.label5.ShowAll();
            // Container child notebook.Gtk.Notebook+NotebookChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.drawBBsToggleButton = new Gtk.ToggleButton();
            this.drawBBsToggleButton.CanFocus = true;
            this.drawBBsToggleButton.Name = "drawBBsToggleButton";
            this.drawBBsToggleButton.UseUnderline = true;
            this.drawBBsToggleButton.Label = Mono.Unix.Catalog.GetString("draw bbs");
            this.table1.Add(this.drawBBsToggleButton);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.drawBBsToggleButton]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.plusSizeButton = new Gtk.Button();
            this.plusSizeButton.CanFocus = true;
            this.plusSizeButton.Name = "plusSizeButton";
            this.plusSizeButton.UseUnderline = true;
            this.plusSizeButton.Label = Mono.Unix.Catalog.GetString("+");
            this.hbox1.Add(this.plusSizeButton);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.plusSizeButton]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.minusSizeButton = new Gtk.Button();
            this.minusSizeButton.CanFocus = true;
            this.minusSizeButton.Name = "minusSizeButton";
            this.minusSizeButton.UseUnderline = true;
            this.minusSizeButton.Label = Mono.Unix.Catalog.GetString("-");
            this.hbox1.Add(this.minusSizeButton);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.minusSizeButton]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.table1.Add(this.hbox1);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.hbox1]));
            w8.TopAttach = ((uint)(2));
            w8.BottomAttach = ((uint)(3));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("draw bbs");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label15 = new Gtk.Label();
            this.label15.Name = "label15";
            this.label15.LabelProp = Mono.Unix.Catalog.GetString("Size");
            this.table1.Add(this.label15);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label15]));
            w10.TopAttach = ((uint)(2));
            w10.BottomAttach = ((uint)(3));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("restart");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.restartLevelButton = new Gtk.Button();
            this.restartLevelButton.CanFocus = true;
            this.restartLevelButton.Name = "restartLevelButton";
            this.restartLevelButton.UseUnderline = true;
            this.restartLevelButton.Label = Mono.Unix.Catalog.GetString("restart");
            this.table1.Add(this.restartLevelButton);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.restartLevelButton]));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            this.notebook.Add(this.table1);
            Gtk.Notebook.NotebookChild w13 = ((Gtk.Notebook.NotebookChild)(this.notebook[this.table1]));
            w13.Position = 1;
            // Notebook tab
            this.sizeLabel = new Gtk.Label();
            this.sizeLabel.Name = "sizeLabel";
            this.sizeLabel.LabelProp = Mono.Unix.Catalog.GetString("me gangster");
            this.notebook.SetTabLabel(this.table1, this.sizeLabel);
            this.sizeLabel.ShowAll();
            this.Add(this.notebook);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 467;
            this.DefaultHeight = 473;
            this.Show();
            this.statsArea.ExposeEvent += new Gtk.ExposeEventHandler(this.drawStatsArea);
            this.restartLevelButton.Activated += new System.EventHandler(this.restartButtonClicked);
            this.plusSizeButton.Clicked += new System.EventHandler(this.plusSizeButtonClicked);
            this.minusSizeButton.Clicked += new System.EventHandler(this.minusSizeButtonClicked);
            this.drawBBsToggleButton.Toggled += new System.EventHandler(this.drawBoundingBoxesToggled);
        }
    }
}
